LOAD DATA LOCAL INFILE "customer.csv"
INTO TABLE customer
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "department.csv"
INTO TABLE department
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "employee.csv"
INTO TABLE employee
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "company.csv"
INTO TABLE company
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "product.csv"
INTO TABLE product
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "game.csv"
INTO TABLE game
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "console.csv"
INTO TABLE console
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "accessory.csv"
INTO TABLE accessory
FIELDS TERMINATED BY ",";

LOAD DATA LOCAL INFILE "transaction.csv"
INTO TABLE transaction
FIELDS TERMINATED BY ",";

